# Generated by Django 3.2.7 on 2021-10-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='default-plant.png', upload_to='plant-pics'),
        ),
    ]
